apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "manga-reader.fullname" . }}-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "manga-reader.fullname" . }}-limit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.domain.web }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "manga-reader.fullname" . }}-web-service
            port:
              number: 80
  - host: {{ .Values.domain.img }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "manga-reader.fullname" . }}-image-processor-service
            port:
              number: 3001
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "manga-reader.fullname" . }}-limit
spec:
  buffering:
    maxRequestBodyBytes: 1073741824 # 1GB
