apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manga-reader.fullname" . }}-pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: manual
  volumeName: {{ include "manga-reader.fullname" . }}-pgdata-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manga-reader.fullname" . }}-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: {{ include "manga-reader.fullname" . }}-uploads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manga-reader.fullname" . }}-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: {{ include "manga-reader.fullname" . }}-cache-pv
