apiVersion: v1
kind: Secret
metadata:
  name: {{ include "manga-reader.fullname" . }}-secrets
stringData:
  POSTGRES_USER: {{ .Values.database.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.postgresPassword | quote }}
  
  WEB_DB_USER: {{ .Values.database.web.user | quote }}
  WEB_DB_PASSWORD: {{ .Values.database.web.password | quote }}
  WEB_DATABASE_URL: "postgres://{{ .Values.database.web.user }}:{{ .Values.database.web.password }}@{{ include "manga-reader.fullname" . }}-postgres:5432/{{ .Values.database.web.db }}"
  
  PROCESSOR_DB_USER: {{ .Values.database.processor.user | quote }}
  PROCESSOR_DB_PASSWORD: {{ .Values.database.processor.password | quote }}
  PROCESSOR_DB_URL: "postgresql://{{ .Values.database.processor.user }}:{{ .Values.database.processor.password }}@{{ include "manga-reader.fullname" . }}-postgres:5432/{{ .Values.database.processor.db }}"
  
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  DISCORD_CLIENT_ID: {{ .Values.secrets.discordClientId | quote }}
  DISCORD_CLIENT_SECRET: {{ .Values.secrets.discordClientSecret | quote }}
  
  S3_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}

  IMAGE_SERVER_API_KEY: {{ .Values.secrets.imageServerApiKey | quote }}
  BOT_SECRET: {{ .Values.secrets.botSecret | quote }}
  MAIL_USER: {{ .Values.secrets.mailUser | quote }}
  POSTFIX_PASSWORD: {{ .Values.secrets.postfixPassword | quote }}
